export {default as Homeslider} from '../components/Homeslider.vue'
export {default as Tips} from '../components/Tips.vue'
export {default as CatalogSlider} from '../components/CatalogSlider.vue'
export {default as Clider} from '../components/Clider.vue'
export {default as Categories} from '../components/Categories.vue'